// <auto-generated />
using Arquivos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Arquivos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArquivosDbContext))]
    [Migration("20260831200000_InitialCreate")]
    public partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            ArquivosDbContextModelSnapshot.BuildArquivosModel(modelBuilder);
        }
    }
}
