// <auto-generated />
using System;
using System.Collections.Generic;
using Arquivos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arquivos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArquivosDbContext))]
    partial class ArquivosDbContextModelSnapshot : ModelSnapshot
    {
        /// <inheritdoc />
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            BuildArquivosModel(modelBuilder);
        }

        internal static void BuildArquivosModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("arquivos")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arquivos.Core.Entities.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CaminhoStorage")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataDesativacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<string>("Extensao")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Dictionary<string, string>>("Metadados")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModuloOrigem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NomeArmazenado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProvedorStorage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SistemaOrigem")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int?>("UsuarioDesativacaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioUploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChecksumSha256");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SistemaOrigem");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("EmpresaId", "Ativo");

                    b.ToTable("arquivos", "arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
